/**
 * Mock Database for Development
 * Provides in-memory data for all models without MongoDB
 * 
 * Usage in development:
 * 1. Keep MONGO_URI commented in .env
 * 2. This module automatically injects mock data
 */

const mockData = {
  users: [
    {
      _id: '507f1f77bcf86cd799439011',
      name: 'Admin User',
      email: 'admin@axentralab.com',
      password: '$2a$12$jX4.YZM8v3LpVjXJZqV3W..fake.hashed.password', // admin123!
      role: 'admin',
      company: 'Axentralab',
      phone: '+8801700000000',
      isActive: true,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      _id: '507f1f77bcf86cd799439012',
      name: 'John Doe',
      email: 'john@example.com',
      password: '$2a$12$fake.hashed.password',
      role: 'client',
      company: 'Tech Corp',
      phone: '+8801600000000',
      isActive: true,
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-02-01'),
    },
  ],
  
  services: [
    {
      _id: '507f1f77bcf86cd799439101',
      title: 'AI Automation',
      slug: 'ai-automation',
      category: 'Automation',
      icon: '⚡',
      color: '#22C55E',
      description: 'Chatbots, workflow automation, CRM integration, and intelligent AI agents.',
      features: ['AI chatbots', 'Workflow automation', 'CRM integration', 'AI agents'],
      plans: [
        { name: 'Starter', price: 499, billing: 'one-time', features: ['1 chatbot', 'Basic workflow', 'Email support'] },
        { name: 'Pro', price: 999, billing: 'one-time', features: ['5 chatbots', 'Advanced workflows', 'Priority support'] },
        { name: 'Enterprise', price: 2499, billing: 'one-time', features: ['Unlimited bots', 'Custom AI', 'Dedicated support'] },
      ],
      isActive: true,
      order: 1,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      _id: '507f1f77bcf86cd799439102',
      title: 'Web Development',
      slug: 'web-development',
      category: 'Development',
      icon: '🌐',
      color: '#3B82F6',
      description: 'MERN apps, SaaS platforms, dashboards, and enterprise-grade websites.',
      features: ['React/Next.js', 'Node.js backend', 'MongoDB', 'Deployment'],
      plans: [
        { name: 'Landing Page', price: 799, billing: 'one-time', features: ['5 sections', 'Responsive', 'SEO ready'] },
        { name: 'Web App', price: 2999, billing: 'one-time', features: ['Full MERN stack', 'Auth', 'Dashboard'] },
        { name: 'SaaS Platform', price: 7999, billing: 'one-time', features: ['Multi-tenant', 'Billing', 'Admin panel'] },
      ],
      isActive: true,
      order: 2,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      _id: '507f1f77bcf86cd799439103',
      title: 'Cybersecurity',
      slug: 'cybersecurity',
      category: 'Security',
      icon: '🛡️',
      color: '#EF4444',
      description: 'Vulnerability scanning, penetration testing, malware removal, security audits.',
      features: ['Pen testing', 'Vuln scanning', 'Security audit', 'Malware removal'],
      plans: [
        { name: 'Basic Audit', price: 399, billing: 'one-time', features: ['Surface scan', 'Report', 'Fix recommendations'] },
        { name: 'Full Pentest', price: 1499, billing: 'one-time', features: ['Deep test', 'OWASP', 'Report'] },
        { name: 'Monitoring', price: 299, billing: 'monthly', features: ['24/7 monitoring', 'Alerts', 'Reports'] },
      ],
      isActive: true,
      order: 3,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      _id: '507f1f77bcf86cd799439104',
      title: 'DevOps & Cloud',
      slug: 'devops-cloud',
      category: 'Infrastructure',
      icon: '☁️',
      color: '#8B5CF6',
      description: 'CI/CD pipelines, cloud automation, containerization, infrastructure monitoring.',
      features: ['CI/CD', 'Docker/K8s', 'Cloud setup', 'Monitoring'],
      plans: [
        { name: 'Setup', price: 699, billing: 'one-time', features: ['CI/CD pipeline', 'Docker setup', 'Monitoring'] },
        { name: 'Full DevOps', price: 1999, billing: 'one-time', features: ['Full infra', 'Auto-scaling', 'Monitoring'] },
        { name: 'Managed', price: 499, billing: 'monthly', features: ['Management', '24/7 support', 'Scaling'] },
      ],
      isActive: true,
      order: 4,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
  ],

  orders: [
    {
      _id: '507f1f77bcf86cd799439201',
      orderNumber: 'ORD-2024-001',
      userId: '507f1f77bcf86cd799439012',
      items: [{ serviceTitle: 'AI Automation - Starter', price: 499, plan: 'Starter' }],
      total: 499,
      status: 'completed',
      paymentStatus: 'paid',
      createdAt: new Date('2024-02-15'),
      updatedAt: new Date('2024-02-20'),
    },
    {
      _id: '507f1f77bcf86cd799439202',
      orderNumber: 'ORD-2024-002',
      userId: '507f1f77bcf86cd799439012',
      items: [{ serviceTitle: 'Web Development - Web App', price: 2999, plan: 'Web App' }],
      total: 2999,
      status: 'pending',
      paymentStatus: 'pending',
      createdAt: new Date('2024-02-25'),
      updatedAt: new Date('2024-02-25'),
    },
  ],

  referrals: [
    {
      _id: '507f1f77bcf86cd799439301',
      referrer: '507f1f77bcf86cd799439011',
      referee: '507f1f77bcf86cd799439012',
      referralCode: 'ADMIN001',
      referralLink: 'http://localhost:3000/register?ref=ADMIN001',
      status: 'completed',
      commissionPercentage: 10,
      commissionAmount: 49.9,
      orderValue: 499,
      activatedAt: new Date('2024-02-01'),
      completedAt: new Date('2024-02-20'),
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-02-20'),
    },
  ],

  blogPosts: [
    {
      _id: '507f1f77bcf86cd799439401',
      title: 'Getting Started with AI Automation',
      slug: 'getting-started-ai-automation',
      content: 'AI automation is transforming how businesses operate. Learn how to leverage it for your business...',
      excerpt: 'Learn how to leverage AI automation to streamline your business processes.',
      category: 'AI Automation',
      tags: ['AI', 'automation', 'beginner'],
      author: '507f1f77bcf86cd799439011',
      cover: '',
      published: true,
      views: 150,
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-01-10'),
    },
    {
      _id: '507f1f77bcf86cd799439402',
      title: 'Building Scalable Web Applications',
      slug: 'building-scalable-web-applications',
      content: 'Scalability should be built into your architecture from day one...',
      excerpt: 'Architecture patterns and best practices for creating web apps that grow with your business.',
      category: 'Web Dev',
      tags: ['web-dev', 'scalability', 'architecture'],
      author: '507f1f77bcf86cd799439011',
      cover: '',
      published: true,
      views: 220,
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
  ],

  leads: [
    {
      _id: '507f1f77bcf86cd799439501',
      name: 'Jane Smith',
      email: 'jane@company.com',
      phone: '+8801700000001',
      company: 'Innovation Inc',
      service: 'Web Development',
      budget: 5000,
      timeline: 'Q1 2024',
      message: 'Looking for MERN stack development for our startup',
      status: 'new',
      score: 85,
      source: 'contact-form',
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-02-20'),
    },
    {
      _id: '507f1f77bcf86cd799439502',
      name: 'Bob Wilson',
      email: 'bob@enterprise.com',
      phone: '+8801800000001',
      company: 'Enterprise Corp',
      service: 'AI Automation',
      budget: 10000,
      timeline: 'Q2 2024',
      message: 'Enterprise chatbot solution needed',
      status: 'qualified',
      score: 92,
      source: 'inbound',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-18'),
    },
  ],
};

module.exports = mockData;
